In [1]:
a=[11,4,56,3,12]
a.append(31)

In [2]:
a

[11, 4, 56, 3, 12, 31]

In [3]:
a.extend([22])
a

[11, 4, 56, 3, 12, 31, 22]

In [4]:
a.insert(2,35)
a

[11, 4, 35, 56, 3, 12, 31, 22]

In [5]:
a.remove(3)


In [6]:
a

[11, 4, 35, 56, 12, 31, 22]

In [7]:
a.pop(2)

35

In [8]:
a

[11, 4, 56, 12, 31, 22]

In [9]:
a.index(56)

2

In [10]:
a.append(56)

In [11]:
a.count(56)

2

In [12]:
a.sort()
a

[4, 11, 12, 22, 31, 56, 56]

In [13]:
a.reverse()
a

[56, 56, 31, 22, 12, 11, 4]

In [14]:
a.clear()

In [15]:
a

[]

In [16]:
stu_names=("sriram","sachin","gopal")
stu_names[1]="abishek"

TypeError: 'tuple' object does not support item assignment

In [17]:
a=[56, 56, 31, 22, 12, 11, 4]
a_set=set(a)

In [18]:
a_set

{4, 11, 12, 22, 31, 56}

In [19]:
dict_1={"name":"sriram","age":23,"city":"Bangalore"}

In [20]:
dict_1

{'name': 'sriram', 'age': 23, 'city': 'Bangalore'}

In [21]:
dict_1["age"]=22

dict_1["email"]="Sriramsv7@gmail.com"

In [22]:
dict_1

{'name': 'sriram',
 'age': 22,
 'city': 'Bangalore',
 'email': 'Sriramsv7@gmail.com'}

In [24]:
age=int(input("enter the age: "))
if age>=18:
    print("eligible to vote")
else:
    print("not eligible")

enter the age:  19


eligible to vote


In [25]:
mark=int(input("enter the mark: "))

if mark >= 90:
    print("A")
elif mark >=75:
    print("B")
elif mark >=50:
    print("C")
else:
    print("Fail")

enter the mark:  65


C


In [26]:
a=int(input("enter the number: "))

if a>0:
    if a%2==0:
        print("number is positive and even number")
    else:
        print("number is positive and odd number")

elif a==0:
    print("number is zero")
else:
    print("number is negative")

enter the number:  56


number is positive and even number


### Section B: Numpy

In [27]:
import numpy as np

In [28]:
np.array(5)

array(5)

In [29]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [31]:
np.arange(10, 61, 10).reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
9) Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [36]:
import numpy as np

random_array = np.random.randint(0,101,size=(4,4))

print(random_array)

[[97 33 16  7]
 [ 3 96 21 90]
 [58 36 64 57]
 [31 62 92 69]]


In [39]:
import pandas as pd

In [43]:
array=np.arange(10, 61, 10).reshape(2, 3)

In [44]:
array

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
column_names = ['A', 'B', 'C']
df = pd.DataFrame(data=array, columns=column_names)

In [42]:
df

A   B   C
0  10  20  30
1  40  50  60

In [73]:
data = {
    'Name': ['Sriram', 'Ravi', 'Sachin', 'Mohan', 'Gopal', 'Rajesh', 'Abishek', 'Vikas', 'RaviKumar', 'Priyan'],
    'Age': [28, 32, 25, 45, 30, 38, 27, 28, 32, 28],
    'City': ['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Hyderabad', 'Delhi', 'Mumbai', 'Bengaluru', 'Delhi', 'Mumbai'],
    'Salary': [600000, 950000, 80000, np.nan, 700000, 1500000, 750000, np.nan, 950000, 600000]
}

In [74]:
df=pd.DataFrame(data=data)

In [75]:
df

Name  Age       City     Salary
0     Sriram   28     Mumbai   600000.0
1       Ravi   32      Delhi   950000.0
2     Sachin   25  Bengaluru    80000.0
3      Mohan   45    Chennai        NaN
4      Gopal   30  Hyderabad   700000.0
5     Rajesh   38      Delhi  1500000.0
6    Abishek   27     Mumbai   750000.0
7      Vikas   28  Bengaluru        NaN
8  RaviKumar   32      Delhi   950000.0
9     Priyan   28     Mumbai   600000.0

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [77]:
df.describe()

Age        Salary
count  10.000000  8.000000e+00
mean   31.300000  7.662500e+05
std     6.019413  4.029866e+05
min    25.000000  8.000000e+04
25%    28.000000  6.000000e+05
50%    29.000000  7.250000e+05
75%    32.000000  9.500000e+05
max    45.000000  1.500000e+06

In [78]:
df[['Name', 'City']]

Name       City
0     Sriram     Mumbai
1       Ravi      Delhi
2     Sachin  Bengaluru
3      Mohan    Chennai
4      Gopal  Hyderabad
5     Rajesh      Delhi
6    Abishek     Mumbai
7      Vikas  Bengaluru
8  RaviKumar      Delhi
9     Priyan     Mumbai

In [79]:
df=df.drop(columns=['City'])

In [80]:
df

Name  Age     Salary
0     Sriram   28   600000.0
1       Ravi   32   950000.0
2     Sachin   25    80000.0
3      Mohan   45        NaN
4      Gopal   30   700000.0
5     Rajesh   38  1500000.0
6    Abishek   27   750000.0
7      Vikas   28        NaN
8  RaviKumar   32   950000.0
9     Priyan   28   600000.0

In [84]:
mean_salary=df["Salary"].mean()
mean_salary
df["Salary"]=df["Salary"].fillna(mean_salary)

In [85]:
df

Name  Age     Salary
0     Sriram   28   600000.0
1       Ravi   32   950000.0
2     Sachin   25    80000.0
3      Mohan   45   766250.0
4      Gopal   30   700000.0
5     Rajesh   38  1500000.0
6    Abishek   27   750000.0
7      Vikas   28   766250.0
8  RaviKumar   32   950000.0
9     Priyan   28   600000.0

In [86]:
df.duplicated().sum()

0